services:
  datahub:
    image: mimiro/datahub:latest
    container_name: datahub
    volumes:
      - ${JELLYFISHHOME}/datahub:/root/datahub
    environment:
      - SERVICE_NAME=datahub
      - SERVER_PORT=4242
      - NODE_ID=dh1
      - SECURITY_STORAGE_LOCATION=/root/datahub/security
      - AUTHORIZATION_MIDDLEWARE=noop
      - STORE_LOCATION=/root/datahub/store
      - ADMIN_USERNAME=
      - ADMIN_PASSWORD=
    ports:
      - "4242:4242"
    restart: unless-stopped

  jellyfish5:
      image: mimiro/objectstorage-datalayer
      container_name: jellyfish
      volumes:
        - ${JELLYFISHHOME}/config:/root/content
        - ${JELLYFISHHOME}/data:/csv
      environment:
        - SERVICE_NAME=jellyfish1
        - CONFIG_LOCATION=file://content/config.json
        - AUTHORIZATION_MIDDLEWARE=noop
        - SERVER_PORT=4344
      ports: 
        - "4344:4344"
      restart: unless-stopped

